export const coursesFromTopTrainers = [
  {
    id: 1,
    courseTitle: 'Usability Testing',
    trainerName: 'Michelle Hunt',
    courseCategory: 'UX Designer',
    signalStregth: 2,
    users: 3,
    rating: 5,
    views: '14',
    price: '45',
    starred: false,
  },
  {
    id: 2,
    courseTitle: 'Why the research matter?',
    trainerName: 'Harry Hudson',
    courseCategory: 'UX/UI Designer',
    signalStregth: 4,
    users: 2,
    rating: 5,
    views: '21',
    price: '30',
    starred: true,
  },
  {
    id: 3,
    courseTitle: 'Desigining the wireframes',
    trainerName: 'Lisa Hoffman',
    courseCategory: 'UX/UI Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '57',
    price: '50',
    starred: false,
  },
  {
    id: 4,
    courseTitle: 'Usability Testing',
    trainerName: 'Michelle Hunt',
    courseCategory: 'UX Designer',
    signalStregth: 2,
    users: 3,
    rating: 5,
    views: '14',
    price: '45',
    starred: false,
  },
  {
    id: 5,
    courseTitle: 'Why the research matter?',
    trainerName: 'Harry Hudson',
    courseCategory: 'UX/UI Designer',
    signalStregth: 4,
    users: 2,
    rating: 5,
    views: '21',
    price: '30',
    starred: true,
  },
  {
    id: 6,
    courseTitle: 'Desigining the wireframes',
    trainerName: 'Lisa Hoffman',
    courseCategory: 'UX/UI Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '57',
    price: '50',
    starred: false,
  },
  {
    id: 7,
    courseTitle: 'Usability Testing',
    trainerName: 'Michelle Hunt',
    courseCategory: 'UX Designer',
    signalStregth: 2,
    users: 3,
    rating: 5,
    views: '14',
    price: '45',
    starred: false,
  },
  {
    id: 8,
    courseTitle: 'Why the research matter?',
    trainerName: 'Harry Hudson',
    courseCategory: 'UX/UI Designer',
    signalStregth: 4,
    users: 2,
    rating: 5,
    views: '21',
    price: '30',
    starred: true,
  },
  {
    id: 9,
    courseTitle: 'Desigining the wireframes',
    trainerName: 'Lisa Hoffman',
    courseCategory: 'UX/UI Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '57',
    price: '50',
    starred: false,
  },
  {
    id: 10,
    courseTitle: 'Usability Testing',
    trainerName: 'Michelle Hunt',
    courseCategory: 'UX Designer',
    signalStregth: 2,
    users: 3,
    rating: 5,
    views: '14',
    price: '45',
    starred: false,
  },
];

export const allCourses = [
  {
    id: 11,
    courseTitle: 'How to write user stories',
    trainerName: 'Matthew Lawson',
    courseCategory: 'Interaction Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '31',
    price: '75',
    starred: false,
  },
  {
    id: 12,
    courseTitle: 'Why do we need the wireframes?',
    trainerName: 'Katherine Wilson',
    courseCategory: 'UX/UI Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '62',
    price: '49',
    starred: true,
  },
  {
    id: 13,
    courseTitle: 'Problem validation',
    trainerName: 'Pamella Collins',
    courseCategory: 'UX Designer',
    signalStregth: 2,
    users: 1,
    rating: 5,
    views: '62',
    price: '49',
    starred: true,
  },
];
